### ISSUE TITLE
Missing cnonce in getAuthorization 

### ISSUE THREAD

**Issue by jmarchand-jive** [RestComm/sipunit#14]
Hello, 

I was trying to use SIPunit 2.0.1 to do a simple REGISTER test and found out that the cnonce and nc-value fields in the Authenticate Header are not implemented, as we can see below. 

See here directly in the code: https://github.com/RestComm/sipunit/blob/011a01f0b3712071d661a54a43cb6b3048764c5f/src/main/java/org/cafesip/sipunit/SipSession.java#L1699

Sorry for the formatting below: 
`public AuthorizationHeader getAuthorization(String method, String uri, String requestBody,
      WWWAuthenticateHeader authHeader, String username, String password) throws SecurityException {
    String response = null;
    try {
      response = MessageDigestAlgorithm.calculateResponse(authHeader.getAlgorithm(), username,
          authHeader.getRealm(), new String(password), authHeader.getNonce(),
          // TODO we should one day implement those two null-s
          null, // nc-value
          null, // cnonce
          method, uri, requestBody, authHeader.getQop());
    } catch (NullPointerException exc) {
      throw new SecurityException(
          "The received authenticate header was malformatted: " + exc.getMessage());
    }`

Using these values is actually a required to authenticate in my case and would block any use of SIPunit I want to make. Is there any plan on addressing this? 

Thank you.

**Comment by deruelle** [comment]
Hi @jmarchand-jive ,

Would you like to contribute a fix and pull request for this ?

You can read our Open Source Playbook for more information https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit?usp=sharing

**Comment by jmarchand-jive** [comment]
Hi @deruelle, 

It's something that we might be looking to do, I was wondering if it was already planned on your side. I'll try to get it working on my machine first and will report back. 

Thank you,
